# Generated by Django 5.2.12 on 2026-04-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingimage_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycarelisting',
            name='place_id',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
    ]
