# Generated by Django 5.2.12 on 2026-04-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_daycarelisting_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycarelisting',
            name='maps_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='daycarelisting',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
