# Generated by Django 5.2.17 on 2026-10-03 08:04

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_daycarelisting_maps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycarelisting',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='When this listing last appeared in an imported scrape.', null=True),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='locked_fields',
            field=models.JSONField(blank=True, default=list, help_text='Fields the importer must not overwrite. Filled automatically when you edit a field in the admin; remove a name to let the next import update it again.'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=listings.models.listing_image_path),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='source URL'),
        ),
    ]
