# Generated by Django 5.2.17 on 2026-10-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_daycarelisting_last_seen_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycarelisting',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='daycarelisting',
            name='hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
