# Generated by Django 5.2.17 on 2026-10-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_daycarelisting_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycarelisting',
            name='listing_type',
            field=models.CharField(choices=[('daycare', 'Daycare'), ('preschool', 'Preschool / Montessori')], db_index=True, default='daycare', max_length=20, verbose_name='type'),
        ),
    ]
