# Generated by Django 5.2.17 on 2026-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_daycarelisting_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycarelisting',
            name='sub_area',
            field=models.CharField(blank=True, help_text='Sub-sector within the area, e.g. "F-7/4". Shown on the listing only.', max_length=50),
        ),
    ]
