# Generated by Django 5.2.17 on 2026-10-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_daycarelisting_sub_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycarelisting',
            name='age_from_months',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='45 days = 1.5', max_digits=4, null=True, verbose_name='youngest age (months)'),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='age_to_months',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='5 years = 60', max_digits=4, null=True, verbose_name='oldest age (months)'),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='curriculum',
            field=models.JSONField(blank=True, default=list, help_text='Keys from CURRICULA, e.g. ["eyfs", "montessori"]'),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='details_checked',
            field=models.DateField(blank=True, help_text='When the details were last checked', null=True),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='details_confirmed',
            field=models.BooleanField(default=False, help_text='Show the details on the site. Leave unticked until checked.'),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='details_source',
            field=models.URLField(blank=True, help_text='Page the details were taken from', max_length=500),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='fees_from_aed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='fees from (AED a year)'),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='fees_note',
            field=models.CharField(blank=True, help_text='What the fees cover, e.g. "3-5 days a week, 2026-27"', max_length=200),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='fees_to_aed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='fees to (AED a year)'),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='licensed_by',
            field=models.CharField(blank=True, choices=[('KHDA', 'KHDA (Dubai)'), ('ADEK', 'ADEK (Abu Dhabi)'), ('SPEA', 'SPEA (Sharjah)'), ('MOE', 'Ministry of Education'), ('other', 'Other')], max_length=10),
        ),
    ]
