# Generated by Django 5.2.17 on 2026-10-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_nursery_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycarelisting',
            name='age_from_months',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='45 days = 1.5', max_digits=5, null=True, verbose_name='youngest age (months)'),
        ),
        migrations.AlterField(
            model_name='daycarelisting',
            name='age_to_months',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='5 years = 60', max_digits=5, null=True, verbose_name='oldest age (months)'),
        ),
    ]
