# Generated by Django 5.2.17 on 2026-10-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_age_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycarelisting',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
