# Generated by Django 5.2.17 on 2026-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_area_region_country_city_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycarelisting',
            name='activities',
            field=models.JSONField(blank=True, default=list, help_text='Keys from ACTIVITIES, e.g. ["ballet_dance", "football"]'),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='facilities',
            field=models.JSONField(blank=True, default=list, help_text='Keys from FACILITIES, e.g. ["outdoor_play", "library"]'),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='meals',
            field=models.BooleanField(blank=True, null=True, verbose_name='meals included'),
        ),
        migrations.AddField(
            model_name='daycarelisting',
            name='transport',
            field=models.BooleanField(blank=True, help_text='Offers transport (school bus)', null=True),
        ),
    ]
