# Generated by Django 5.2.17 on 2026-10-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_services_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycarelisting',
            name='sub_area',
            field=models.CharField(blank=True, help_text='Part of the area, e.g. "Al Barsha 1". Shown on the listing only.', max_length=50),
        ),
    ]
